### ISSUE TITLE
ìFileNotFoundException: resources/application.properties

### ISSUE THREAD

**Issue by adrianospinoso** [pagopa/pagopa-toolkit-os-codebase#16]
Vorrei utilizzare il toolkit come dipendenza all'interno di un progetto Maven.
Ho scaricato il repository e l'ho installato seguendo le indicazioni.
Ho creato un progetto Maven e ho aggiunto il jar come dipendenza.
Appena cerco di generare un codice IUV ricevo il messaggio in oggetto.
Ho provato a mettere il file all'interno del classpath ma ho sempre lo stesso errore.

**Comment by adrianospinoso** [comment]
Ho risolto spostando il file nella home del progetto.
Mi chiedevo se il toolkit da solo un esempio di come generare lo IUV?
Va realizzata  una implementazione custom dell'interfaccia IuvSequenceReader?

**Comment by pasqualespica** [comment]
> Vorrei utilizzare il toolkit come dipendenza all'interno di un progetto Maven.
> Ho scaricato il repository e l'ho installato seguendo le indicazioni.
> Ho creato un progetto Maven e ho aggiunto il jar come dipendenza.
> Appena cerco di generare un codice IUV ricevo il messaggio in oggetto.
> Ho provato a mettere il file all'interno del classpath ma ho sempre lo stesso errore.

Ciao @adrianospinoso non serve che tu lo faccia a mano se segui il `README` nella sezione [Run Gui](https://github.com/pagopa/pagopa-toolkit-os-codebase#run-gui) c'è un script che lo fa estraendo la cartella `resources` dal `jar`. E' stato testato su `Linux/MacOs` con `start_pagoPA_wizard_gui`

**Comment by pasqualespica** [comment]
> IuvSequenceReader

Quella proposta è un metodo ci come realizzare uno `IUV` in modo unico, nell'esempio l'implementazione dell'interfaccia a cui fai riferimento utilizza proprio il file `application.properties` per fare quello

**Comment by pasqualespica** [comment]
Far riferimento al `README` sezione [Run Gui](https://github.com/pagopa/pagopa-toolkit-os-codebase#run-gui) c

**Comment by adrianospinoso** [comment]
@pasqualespica Grazie per il supporto!

**Comment by pasqualespica** [comment]
> Vorrei utilizzare il toolkit come dipendenza all'interno di un progetto Maven.
> Ho scaricato il repository e l'ho installato seguendo le indicazioni.
> Ho creato un progetto Maven e ho aggiunto il jar come dipendenza.
> Appena cerco di generare un codice IUV ricevo il messaggio in oggetto.
> Ho provato a mettere il file all'interno del classpath ma ho sempre lo stesso errore.

Non vedo il messaggio @adrianospinoso . Ma se metti tutto disponibile sul tuo account `github` in modo da poterlo replicare anche io sul mio pc, provo capire il problema e indirizzarti

**Comment by adrianospinoso** [comment]
> > Vorrei utilizzare il toolkit come dipendenza all'interno di un progetto Maven.
> > Ho scaricato il repository e l'ho installato seguendo le indicazioni.
> > Ho creato un progetto Maven e ho aggiunto il jar come dipendenza.
> > Appena cerco di generare un codice IUV ricevo il messaggio in oggetto.
> > Ho provato a mettere il file all'interno del classpath ma ho sempre lo stesso errore.
> 
> Non vedo il messaggio di errore @adrianospinoso . Ma se metti tutto disponibile sul tuo account `github` in modo da poterlo replicare anche io sul mio pc, provo capire il problema e indirizzarti

Grazie @pasqualespica, non occorre, dovrei aver risolto il problema, tanto più che comunque sia dovrò mettere in piedi un meccanismo interno la generazione dello IUV.
